### ISSUE TITLE
URL issues in head

### ISSUE THREAD

**Issue by Wulfheart** [laravel-frontend-presets/tall#37]
There are some problems if you don't use your app at a root domain, e.g. ``your-app.test/test``, then the asset and mix files won't get recognized. This can get fixed with the function ``url()``.

**Comment by imliam** [comment]
From what I understand, this is more an issue for Laravel to handle than this preset in particular. By default, we use Laravel's built-in `mix()` function to link to assets, which expects the site to be at the root level of the domain.

Swapping this to use the `url()` function is not a fix as that wouldn't generate links with hashes that are used for cache-busting.

Going to close this because I don't think it's something that's a concern for the preset, but feel free to reopen if I've gotten it wrong.
