### ISSUE TITLE
Login component cannot authenticate

### ISSUE THREAD

**Issue by sunlight** [laravel-frontend-presets/tall#66]
I'm using TALL v2.0.0 on Laravel 8, fresh install with auth.

First attempt at logging in via the Login component, I got the following error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'remember' in 'where clause' (SQL: select * from `users` where `email` = blah@example.com and `remember` = 0 limit 1)

This appears to be due to the validation in the Login component's `authenticate()` method:

```php
$credentials = $this->validate([
    'email' => ['required', 'email'],
    'password' => ['required'],
]);
```
It seems `$this->validate()` will return _all_ public members of the component class, whether they are listed in the validation rules or not. The `$remember` member therefore gets sent to `Auth::attempt()` so it adds it into the `users` query.

If this is desired behaviour by Livewire, then the issue is with the component needing to restrict `$credentials` to the keys in the rules array only. If this isn't desired behaviour then I guess this is a Livewire bug?

**Comment by ryangjchandler** [comment]
@sunlight This needs to be reproduced & confirmed but it looks like there have been some changes to how Livewire handles validation, with regards to data passed so it's possible was is a regression on their end, instead of ours. 

Will try & take a look tomorrow, unless somebody else can reproduce perhaps on a Playground or something.

**Comment by sunlight** [comment]
At the moment simply running phpunit on a fresh TALL install fails with that same error.

**Comment by alshamsan** [comment]
@sunlight 

This is actually due to the new logic for `validate()` method of livewire, it returns ALL class properties (probably a bug!) .
if you try `dd($credentials)` you will find it contains a `remember` property, which is causing the error.

@ryangjchandler  I would recommend using the new `$rules` property for livewire validation ([see the docs](https://laravel-livewire.com/docs/2.x/input-validation)).

To solve this just add a `$rules` property like so:
``` php
    protected $rules = [
        'email' => 'required|email',
        'password' => 'required',
    ];
```
Then use the `$this->validate()` inside the `authenticate()` method:

```php
    public function authenticate()
    {
        $this->validate();
        $credentials = ['email' => $this->email, 'password' => $this->password];

        if (!Auth::attempt($credentials, $this->remember)) {
            $this->addError('email', trans('auth.failed'));

            return;
        }

        return redirect()->intended(route('home'));
    }
```

Hope this helps.

**Comment by ryangjchandler** [comment]
Yeah, to me the `validate()` method shouldn't return ALL of the data, since that behaviour actually differs from the normal Laravel validator. Like you said, we could switch to something like you have done with `$this->validate()` and `$rules`, or perhaps `$this->validateOnly()` will still return the correct data.

**Comment by alshamsan** [comment]
@ryangjchandler 
Agree. This is actually misleading at livewire's end. this behavior is caused by ` $this->getDataForValidation($rules)` call at `validate($rules = null, $messages = [], $attributes = [])` function in `Livewire\ComponentConcerns\ValidatesInput`. 

Strangely enough, `$this->validateOnly()` would accept a single property as parameter, so you'd have to call it twice for `email` and `password` each,  which is a bit verbose.

I'd suggest to follow the latest docs approach by defining a `$rules` property and using the `$this->validate()` to avoid any mishaps in the future.

**Comment by sunlight** [comment]
I don't quite understand why they did this - it looks like their latest commit (bumping to v2.2.5) purposely changed `getDataForValidation()` from returning only the properties references by `$rules`'s keys, to doing what it does now & returning all. So TALL should work fine with Livewire 2.2.4 but not with 2.2.5.
